### ISSUE TITLE
Stop spamming users about your library

### ISSUE THREAD

**Issue by anaisbetts** [IgorBuchelnikov/ObservableComputations#12]
Cold Emailing people by scraping GitHub is against the ToS and is a Generally Shitty Thing To Do. Please stop messaging people who have not asked for your spam.

**Comment by IgorBuchelnikov** [comment]
I understand your concern. The main reason for your concern is not my mailing activity, but the fact that I am your competitor, since you are promoting [ReativeUI](https://github.com/reactiveui/reactiveui#core-team). I disagree that my mailing activity is spam. I do not violate the CAN-SPAM Act:
* my emails 
  * is targeted to software developers, 
  * is not anonymous
  * does not contain libel, does not mislead
* I  do not send more than one email to one addressee
* I do  explore commercial benefits

For more info, please, read https://blog.zoominfo.com/is-cold-email-spam/

**Comment by anaisbetts** [comment]
The main reason for my concern is that I'm getting Email from you and I did not ask for it. Stop.

**Comment by IgorBuchelnikov** [comment]
OK. Send your email addresses to observablecomputations@gmail.com and I will never send you emails

**Comment by IgorBuchelnikov** [comment]
Sorry, the email you received was the last one from me. If you have many other email addresses, I cannot help you.
