### ISSUE TITLE
Please add a change log or release notes document

### ISSUE THREAD

**Issue by factormystic** [IgorBuchelnikov/ObservableComputations#6]
Hi, could you consider adding a changelog file to this repo? For example it'd be nice to know what changed between v1.3.0 and v1.4.0, but this doesn't appear to be documented anywhere, and there's no release notes, and the commit history looks like this:

![image](https://user-images.githubusercontent.com/43428/89721323-367c3980-d9aa-11ea-8ec4-6b958b215ee0.png)

Thanks!

**Comment by IgorBuchelnikov** [comment]
Hi!
Any NuGet package has release notes as meta info. I add that info to every my nuget package.
You can see release notes of the all nuget packages [here](https://www.nuget.org/packages/ObservableComputations/)
![2020-08-10_11-45-11](https://user-images.githubusercontent.com/1316068/89766031-20808d00-db00-11ea-9670-911d0e666a26.png)
I write release notes briefly. You can see more details in the [user documentation](https://github.com/IgorBuchelnikov/ObservableComputations/blob/master/README.md) or in the code.

I don't see any point in writing detailed comments on commits now, since
* they can only contain a description of the internal implementation (all other info in the release notes)
* no documentation on internal implementation
* I'm the only developer
In case anyone adds issue and I will commit to resolve it, I add a reference to that issue to the commit description.

**Comment by factormystic** [comment]
Thanks, I somehow didn't see the change log on nuget.org. I don't often visit that website, since I'm either looking at the github repo or updating the package from visual studio (which doesn't appear to show those notes). In the future if you tag releases on github, it'd be nice to also see those change log notes in the release notes, but currently, this is what I was looking for, thanks!
